
all: technical_drawing-mcmaster.pdf

technical_drawing-mcmaster.pdf:
	wget "https://www.mcmaster.com/mvA/library/20140203/91290A125_BLACK-OXIDE%20CLASS%2012.9%20SOCKET%20HEAD%20CAP%20SCREW.PDF" --output-document=$@

